// SPDX-License-Identifier: GPL-3.0-or-later
// Generated from renderer/laniakea-renderer.gs

export const RENDERER_VERSION = '2';
export const RENDERER_SCRIPT = [
    "#!/usr/bin/gjs -m",
    "// SPDX-License-Identifier: GPL-3.0-or-later",
    "",
    "import Cairo from 'gi://cairo';",
    "import Gdk from 'gi://Gdk?version=4.0';",
    "import Gio from 'gi://Gio';",
    "import GLib from 'gi://GLib';",
    "import GObject from 'gi://GObject';",
    "import Gtk from 'gi://Gtk?version=4.0';",
    "import WebKit from 'gi://WebKit?version=6.0';",
    "import System from 'system';",
    "",
    "const APPLICATION_ID = 'io.github.visnudeva.LaniakeaRenderer';",
    "const SETTINGS_SCHEMA = 'org.gnome.shell.extensions.laniakea';",
    "const RELOAD_SCRIPT = 'if (typeof resetDrawing === \"function\") resetDrawing();';",
    "const RELOAD_MAX_ATTEMPTS = 8;",
    "const RELOAD_RETRY_MS = 200;",
    "const RESUME_RELOAD_DEBOUNCE_MS = 300;",
    "",
    "function readExtensionConfig(extensionPath = '') {",
    "    const defaults = {maskMode: 'circle'};",
    "",
    "    if (!extensionPath)",
    "        return defaults;",
    "",
    "    const schemaDir = GLib.build_filenamev([extensionPath, 'schemas']);",
    "    if (!GLib.file_test(schemaDir, GLib.FileTest.IS_DIR))",
    "        return defaults;",
    "",
    "    try {",
    "        const source = Gio.SettingsSchemaSource.new_from_directory(",
    "            schemaDir,",
    "            Gio.SettingsSchemaSource.get_default(),",
    "            false,",
    "        );",
    "        const schema = source.lookup(SETTINGS_SCHEMA, true);",
    "        if (!schema)",
    "            return defaults;",
    "",
    "        const settings = new Gio.Settings({settings_schema: schema});",
    "        let maskMode = settings.get_string('draw-mask-mode');",
    "        if (maskMode === 'none')",
    "            maskMode = 'wide';",
    "",
    "        return {maskMode};",
    "    } catch {",
    "        return defaults;",
    "    }",
    "}",
    "",
    "function buildConfigScript(config) {",
    "    return (",
    "        `window.LANIAKEA_CONFIG = ${JSON.stringify(config)};` +",
    "        'if (typeof applyLaniakeaConfig === \"function\") applyLaniakeaConfig();'",
    "    );",
    "}",
    "",
    "const LaniakeaRendererWindow = GObject.registerClass({",
    "}, class LaniakeaRendererWindow extends Gtk.ApplicationWindow {",
    "    constructor(app, monitor, index, htmlUri, extensionPath, nohide = false) {",
    "        const geometry = monitor.get_geometry();",
    "        const state = {",
    "            position: [geometry.x, geometry.y],",
    "            keepAtBottom: true,",
    "            keepMinimized: true,",
    "            keepPosition: true,",
    "        };",
    "        const title = nohide",
    "            ? `Laniakea Renderer #${index}`",
    "            : `@${APPLICATION_ID}!${JSON.stringify(state)}|${index}`;",
    "",
    "        super({",
    "            application: app,",
    "            title,",
    "            decorated: nohide,",
    "            default_width: geometry.width,",
    "            default_height: geometry.height,",
    "        });",
    "",
    "        this.monitor_index = index;",
    "        this._extensionPath = extensionPath;",
    "        this._nohide = nohide;",
    "        this._resumeReloadId = 0;",
    "        this._webviewWasUnmapped = false;",
    "        this.set_resizable(false);",
    "        this.set_size_request(geometry.width, geometry.height);",
    "",
    "        const settings = WebKit.Settings.new();",
    "        settings.set_enable_javascript(true);",
    "        settings.set_enable_developer_extras(false);",
    "",
    "        this._webview = new WebKit.WebView();",
    "        this._webview.set_settings(settings);",
    "        this._webview.connect('load-changed', this._onLoadChanged.bind(this));",
    "        this._webview.connect('notify::mapped', this._onWebviewMapped.bind(this));",
    "        this._webview.load_uri(htmlUri);",
    "        this.set_child(this._webview);",
    "",
    "        this.connect('realize', this._onRealize.bind(this));",
    "        this.connect('notify::visible', this._onVisibleChanged.bind(this));",
    "    }",
    "",
    "    _clearInputRegion() {",
    "        const surface = this.get_surface();",
    "        if (!surface)",
    "            return;",
    "",
    "        surface.set_input_region(new Cairo.Region());",
    "    }",
    "",
    "    _onRealize(window) {",
    "        const monitor = window.get_display().get_monitors().get_item(window.monitor_index);",
    "        const geometry = monitor.get_geometry();",
    "        window.set_default_size(geometry.width, geometry.height);",
    "",
    "        if (!this._nohide)",
    "            this._clearInputRegion();",
    "    }",
    "",
    "    _onLoadChanged(_webview, loadEvent) {",
    "        if (loadEvent === WebKit.LoadEvent.FINISHED)",
    "            this.applyConfig();",
    "    }",
    "",
    "    _onWebviewMapped(webview) {",
    "        if (webview.get_mapped()) {",
    "            if (this._webviewWasUnmapped)",
    "                this._scheduleResumeReload();",
    "            return;",
    "        }",
    "",
    "        this._webviewWasUnmapped = true;",
    "    }",
    "",
    "    _onVisibleChanged() {",
    "        if (!this.get_visible())",
    "            return;",
    "",
    "        if (!this._nohide)",
    "            this._clearInputRegion();",
    "        this._scheduleResumeReload();",
    "    }",
    "",
    "    _scheduleResumeReload() {",
    "        if (this._resumeReloadId)",
    "            GLib.source_remove(this._resumeReloadId);",
    "",
    "        this._resumeReloadId = GLib.timeout_add(",
    "            GLib.PRIORITY_DEFAULT,",
    "            RESUME_RELOAD_DEBOUNCE_MS,",
    "            () => {",
    "                this._resumeReloadId = 0;",
    "                this.reload();",
    "                return GLib.SOURCE_REMOVE;",
    "            },",
    "        );",
    "    }",
    "",
    "    _evaluate(script, onError = null) {",
    "        this._webview.evaluate_javascript(",
    "            script,",
    "            -1,",
    "            null,",
    "            null,",
    "            null,",
    "            (_webview, result) => {",
    "                try {",
    "                    _webview.evaluate_javascript_finish(result);",
    "                } catch {",
    "                    onError?.();",
    "                }",
    "            },",
    "        );",
    "    }",
    "",
    "    applyConfig() {",
    "        const config = readExtensionConfig(this._extensionPath);",
    "        this._evaluate(buildConfigScript(config));",
    "    }",
    "",
    "    reload(attempt = 0) {",
    "        this._evaluate(RELOAD_SCRIPT, () => {",
    "            if (attempt + 1 < RELOAD_MAX_ATTEMPTS) {",
    "                GLib.timeout_add(GLib.PRIORITY_DEFAULT, RELOAD_RETRY_MS, () => {",
    "                    this.reload(attempt + 1);",
    "                    return GLib.SOURCE_REMOVE;",
    "                });",
    "            }",
    "        });",
    "    }",
    "});",
    "",
    "const LaniakeaRendererApp = GObject.registerClass({",
    "}, class LaniakeaRendererApp extends Gtk.Application {",
    "    constructor() {",
    "        super({",
    "            application_id: APPLICATION_ID,",
    "            flags: Gio.ApplicationFlags.HANDLES_COMMAND_LINE,",
    "        });",
    "",
    "        this.extensionPath = '';",
    "        this.nohide = false;",
    "        this._windows = [];",
    "",
    "        this.add_main_option(",
    "            'path', charCodeAt('P'), GLib.OptionFlags.NONE, GLib.OptionArg.STRING,",
    "            'Extension directory path', 'PATH',",
    "        );",
    "        this.add_main_option(",
    "            'nohide', charCodeAt('N'), GLib.OptionFlags.NONE, GLib.OptionArg.NONE,",
    "            'Show renderer window for debugging', null,",
    "        );",
    "",
    "        this.connect('command-line', this._onCommandLine.bind(this));",
    "        this.connect('startup', this._onStartup.bind(this));",
    "        this.connect('activate', this._onActivate.bind(this));",
    "    }",
    "",
    "    _onStartup() {",
    "        const reloadAction = Gio.SimpleAction.new('reload', GLib.VariantType.new('i'));",
    "        reloadAction.connect('activate', this._onReload.bind(this));",
    "        this.add_action(reloadAction);",
    "",
    "        const reloadAllAction = Gio.SimpleAction.new('reload-all', null);",
    "        reloadAllAction.connect('activate', this._onReloadAll.bind(this));",
    "        this.add_action(reloadAllAction);",
    "",
    "        const configureAction = Gio.SimpleAction.new('configure', null);",
    "        configureAction.connect('activate', this._onConfigure.bind(this));",
    "        this.add_action(configureAction);",
    "    }",
    "",
    "    _onReload(_action, param) {",
    "        const index = param?.get_int32() ?? -1;",
    "        for (const window of this._windows) {",
    "            if (window.monitor_index === index) {",
    "                window.reload();",
    "                return;",
    "            }",
    "        }",
    "    }",
    "",
    "    _onReloadAll() {",
    "        for (const window of this._windows)",
    "            window.reload();",
    "    }",
    "",
    "    _onConfigure() {",
    "        for (const window of this._windows)",
    "            window.applyConfig();",
    "    }",
    "",
    "    _onCommandLine(_app, commandLine) {",
    "        const options = commandLine.get_options_dict();",
    "        this.extensionPath = parseExtensionPath(options, commandLine);",
    "        this.nohide = options.contains('nohide');",
    "",
    "        if (!this.extensionPath) {",
    "            console.error('Missing --path argument');",
    "            return 1;",
    "        }",
    "",
    "        this.activate();",
    "        return 0;",
    "    }",
    "",
    "    _onActivate() {",
    "        if (this._windows.length)",
    "            return;",
    "",
    "        const display = Gdk.Display.get_default();",
    "        if (!display)",
    "            return;",
    "",
    "        const htmlPath = GLib.build_filenamev([this.extensionPath, 'index.html']);",
    "        const htmlUri = GLib.filename_to_uri(htmlPath, null);",
    "        const monitors = display.get_monitors();",
    "",
    "        for (let index = 0; index < monitors.get_n_items(); index++) {",
    "            const monitor = monitors.get_item(index);",
    "            const window = new LaniakeaRendererWindow(",
    "                this,",
    "                monitor,",
    "                index,",
    "                htmlUri,",
    "                this.extensionPath,",
    "                this.nohide,",
    "            );",
    "            this._windows.push(window);",
    "            window.present();",
    "        }",
    "    }",
    "});",
    "",
    "function charCodeAt(letter) {",
    "    return letter.charCodeAt(0);",
    "}",
    "",
    "function parseExtensionPath(options, commandLine) {",
    "    if (options.contains('path')) {",
    "        const value = options.lookup_value('path', null).unpack();",
    "        if (typeof value === 'string' && value.length)",
    "            return value;",
    "    }",
    "",
    "    const args = commandLine.get_arguments();",
    "    for (let index = 0; index < args.length - 1; index++) {",
    "        if (args[index] === '--path')",
    "            return args[index + 1];",
    "    }",
    "",
    "    return '';",
    "}",
    "",
    "const app = new LaniakeaRendererApp();",
    "System.exit(app.run(System.programArgs));",
    ""
].join('\n');
